language: python
python:
- 3.6
install:
- pip install -U tox-travis
- pip install -r requirements.txt
- pip install -e .
env:
  global:
  - secure: czUWqYCqNVhsja40NzF25V/JALMR4ys1YOYfD/MoRsoUMEz18Kxl1nHYeA9RB5/D/mVTPvDooz84khu0cnlZj8mXQozYTJg3IbMr5RNcSZrrbx+dUKrA7c0W0kZBPXXM5edG/ovkzrcry5kl9Te5x0dMIICwU5ZT950SMNgtabR3GoIGlNv3Qw6zAb+8GUmqtp0BagmSZpliOePoVi7ZZVS4jYf+QWB/Q54W0SlX2oso5d46LIVBYWANiD68eV/99GqlqMXOO1p7Py7okFPDq6eEsvf0pkf4o/ky6U0/y23LLb1ayDwzkuboOAhCxSkPqX1wTzbwYkF6gjuuZp98H4y2qoMV8jzZAQ183v1w+fxGZFE+rF7Sn7Lg9EFZh1pH3D3S04oV92mnJtf10STmWeyEaQdJhe/NHHPCPlxMf3XV2WXweSvmOaEobKf3KDFSj5J8OO5hb9otnD6D7mVbdS9tFbqWF3mwZNuegv6psdW03OpBI86Xu+aXBiykPgqz4/cZTIHf7Q0YZic7LgP3FHd02f0kIGcbS6UjSHQtIHu8mDD7KF9gsZbxll5ukgN1dxz+EvU1ZfzKyKbWoCFrsVNOiRcq5U6WWDwWTV/EzShFVTOFnQw5J3U91KheptMMBBYwEr0NC/c7vUsS1W66OJF8ggL9AdCrkl2hItZyGLk=
script:
- pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: MJPMPC
  password:
    secure: vKZPqZhChYP7ZHkqvlA30INlih85//VcC9Ma9PcDqZhCPvj1dmGDREBNZh19ZDaXnHOQNLL+EKajsKMMFdxRNkX7+A0L1f93m42GLEio4hrN4XvqxZuWdWsVBs1Zd32O7f5mJTJKczMpKkjmHn1EoXJ4QdNTRFN07Nx+0PLoOoa1yyswQSb5a+ViZhUHKfG0G4U4GR9DANCjDKl7g6nz7otlFX9jVVRfNxlhm2eGDk4C4VIirR7gntP+kRDr59DBPWISX+9grsXQGXedQ2glOtmRJnJcoETpEaGzxOnE/1bdKMo4CaUEa2A6GjgRMxQnpWEec8dH7e3EDYZdeyPh6+EJcPvHTY8ONaNOzKpUDDbUr2CUWFKGABcI4+cbrc5k3rQeGiw4tvXIUdzf0vNjy2Z+Y1u/30ssH9A4IXX5iXW683TjZFYEAKmRYkf72sDibwUiZ/Qq+7WOCkQhdyoyBzUC+Ts/TpsDDVCcIehbqQBPZ3TGwhsp04GztoyZ92XnAElPv614Wj55k+HuUpNrvK6IEKaQ6ELVUo8CQEe11YaFxNNxAHC3a0FnzHmiFXnNuWsB6m8B6okzO8sM1MXVfqwQ8pEAIjidQZDVETF9kMdcrKpgknqVFIQTmSBcsP23yil/RZDlEhen05mFdBk8U/AfmbVPGGlCEdxRUYWqv74=
